<template>
  <!-- <div id="fullCover">
      <div id="loadLoader"></div>
  </div> -->
  <div  class="loadingio-spinner-interwind-46tfzgunr0x">
    <div class="ldio-oe1ega0nt1">
      <div>
        <div>
          <div><div></div></div>
        </div>
        <div>
          <div><div></div></div>
        </div>
      </div>
    </div>
  </div>
</template>

<style type="text/css">
@keyframes ldio-oe1ega0nt1-r {
  0%,
  100% {
    animation-timing-function: cubic-bezier(0.2 0 0.8 0.8);
  }
  50% {
    animation-timing-function: cubic-bezier(0.2 0.2 0.8 1);
  }
  0% {
    transform: rotate(0deg);
  }
  50% {
    transform: rotate(180deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
@keyframes ldio-oe1ega0nt1-s {
  0%,
  100% {
    animation-timing-function: cubic-bezier(0.2 0 0.8 0.8);
  }
  50% {
    animation-timing-function: cubic-bezier(0.2 0.2 0.8 1);
  }
  0% {
    transform: translate(-30px, -30px) scale(0);
  }
  50% {
    transform: translate(-30px, -30px) scale(1);
  }
  100% {
    transform: translate(-30px, -30px) scale(0);
  }
}
.ldio-oe1ega0nt1 > div {
  transform: translate(0px, -15px);
}
.ldio-oe1ega0nt1 > div > div {
  animation: ldio-oe1ega0nt1-r 1s linear infinite;
  transform-origin: 100px 100px;
}
.ldio-oe1ega0nt1 > div > div > div {
  position: absolute;
  transform: translate(100px, 82px);
}
.ldio-oe1ega0nt1 > div > div > div > div {
  width: 60px;
  height: 60px;
  border-radius: 50%;
  background: #fe718d;
  animation: ldio-oe1ega0nt1-s 1s linear infinite;
}
.ldio-oe1ega0nt1 > div > div:last-child {
  animation-delay: -0.5s;
}
.ldio-oe1ega0nt1 > div > div:last-child > div > div {
  animation-delay: -0.5s;
  background: #46dff0;
}
.loadingio-spinner-interwind-46tfzgunr0x {
  width: 100%;
  height: 100%;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-oe1ega0nt1 {
  width: 200px;
  height: 200px;
  left:50%;
  top:50%;
  position: relative;
  transform: translate(-50%,-50%) translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-oe1ega0nt1 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>

<style>
#fullCover {
  position: absolute;
  top: 0;
  left: 0;
  /* padding-left: 5%; */
  height: 100% !important;
  width: 100% !important;
  background-color: white;
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 9999 !important;
}
#loadLoader {
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #007892;
  border-bottom: 16px solid #007892;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite;
  animation: spin 2s linear infinite;
}

@-webkit-keyframes spin {
  0% {
    -webkit-transform: rotate(0deg);
  }
  100% {
    -webkit-transform: rotate(360deg);
  }
}

@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
</style>
